version: '3.3'

services:
  mongodb:
    image: mongo:latest
    container_name: challange-accounts-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: caj
    ports:
      - 27017:27017
    command: mongod --auth